version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=BD2020
      - MYSQL_DATABASE=BD20_clasicos
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
